only_rules:
  - closing_brace
  - empty_enum_arguments
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - trailing_newline
  - unused_import
  - unused_declaration

included:
  - Sources

excluded:
  - Tests
  - .build
  - DerivedData
  - Package.swift

line_length: 500
function_body_length: 500
type_body_length: 500
file_length: 2000

reporter: "github-actions-logging" 