# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - force_cast
  - force_try
  - identifier_name
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - todo
  - trailing_comma
  - nesting

# paths to include during linting. `--path` argument is ignored if present.
included:
  - Sources

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Tests
  - .build
  - DerivedData
  - Package.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning
force_try: warning
line_length: 200
function_body_length: 100
type_body_length: 500
file_length: 1000

reporter: "github-actions-logging" 