name: iOS CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app
        
      - name: Build
        run: |
          xcodebuild clean build -scheme PantryPlus2 \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
            
      - name: Run tests
        run: |
          xcodebuild test -scheme PantryPlus2 \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1 